### ISSUE TITLE
Teensy 4.1 USB Device Pins Backwards

### ISSUE THREAD

**Issue by vjmuzik** [XenGi/teensy.pretty#12]
After receiving a batch of boards with a place to add a more robust USB C connector and not being able to get said connector working I finally dialed down the issue with a USB tester to the D+ and D- lines being backwards. After double checking my schematics and verifying them as correct I took a look at the footprints that were being used and sure enough after a quick cross reference with the Teensy 4.1 schematic I can see that the pins are indeed backwards. D+ should be on the side closest to ground and it's notably on the side closest to VIN on the current footprint. Luckily for me I was already using hookup wire to the connector because of an export error that rendered the traces going to it unusable in the first place so I could easily switch the wires and get it working.

**Comment by blackketter** [comment]
Good find!  I see that you are right.  If you have a patch, feel free to submit it.  Otherwise, I'll take a look in a bit.
