### ISSUE TITLE
Missing SMT pads on the back of Teensy 3.0, 3.1 and 3.2

### ISSUE THREAD

**Issue by jbabio** [XenGi/teensy.pretty#13]
Teensy models 3.0, 3.1 and 3.2 do have 14 pads to solder a row of 2x7 SMT pin header on the back (LC doesn't). Would be nice to have those pins on the footprint to be able to route the tracks to them.

I suggest to have one footprint for the LC and another for the 3.0, 3.1 and 3.2.

https://www.pjrc.com/store/teensy32.html

**Comment by blackketter** [comment]
There is a separate Teensy LC footprint, but you are right, the 3.x footprint should have the bottom pads (and remove the label for LC.). I'll take a look.

**Comment by blackketter** [comment]
I've created a new footprint called Teensy30_31_32_All_Pins and updated the Teensy 3.2 symbol to include PIN numbers for all pins.  Previews:

![Screen Shot 2021-01-21 at 10 44 23 AM](https://user-images.githubusercontent.com/131679/105397864-75a7eb00-5bd6-11eb-94c5-b16089f4c7a2.png)
![Screen Shot 2021-01-21 at 10 43 51 AM](https://user-images.githubusercontent.com/131679/105397871-780a4500-5bd6-11eb-8570-23ebf4f5f0ed.png)

How does this look?

**Comment by jbabio** [comment]
It looks great! I'm looking forward to use them.

**Comment by blackketter** [comment]
Ok, I've pushed the changes to this repo and teensy.library.  Try them out and reopen this issue if there are any problems!
