### ISSUE TITLE
Teensy.mod flawed

### ISSUE THREAD

**Issue by f1gwr** [XenGi/teensy.pretty#15]
### KiCad 5.1.6-0 Mac OS X 10.13.6
Hi,
The .mod file for Teensy 3.2 I tried to include in my Kicad contains text from the web page that should not be there. Sample below (beginning of the file):
----------------------------------------------------
Skip to content

￼
	•	  In this repository All GitHub ↵  Jump to ↵  
	•	No suggested jump to results 
	•	  In this repository All GitHub ↵  Jump to ↵  
	•	  In this user All GitHub ↵  Jump to ↵  
	•	  In this repository All GitHub ↵  Jump to ↵  
	•	
Dashboard Pull requests Issues
Marketplace 
Explore Codespaces Sponsors Settings ￼ f1gwr
Sign out 

New repository Import repository New gist New organization 
￼ 

Sorry, something went wrong. 

XenGi / teensy.pretty 
(...)
----------------------------------------------------
Like the .lib  file, I tried to remove that text to allow the following one as is the sole accepted as a first line:
(module Teensy30_31_32_LC (layer F.Cu) (tedit 606F5D71)
But when saved, will no more be accepted.

**Comment by XenGi** [comment]
I think this is the same issue as you wrote in the other ticket. Let's try to focus on the issue in the other one and have only one discussion. I will close this here.
