### ISSUE TITLE
Teensy 4.1 STEP Model

### ISSUE THREAD

**Issue by kirilian** [XenGi/teensy.pretty#16]
Hello...it appears there may be a slight issue with the Teensy 4.1 3D STEP file.  The 6-pin ethernet footprint appears to be slightly different from the actual Teensy 4.1 module.  According to the PJRC website, the center of the 6-pin footprint should be **4.45**mm from the top 24-pin 'row'.  In the STEP model, the center of the 6-ping footprint is **4.54**mm from the 24-pin row.  It looks like when the 3D model was created, there may have been a typo in the dimensioning/positioning of the 6-pin header.

**Comment by kroko** [comment]
4.45mm [Teensy_4.1_Assembly.STEP.zip](https://github.com/XenGi/teensy.pretty/files/12242739/Teensy_4.1_Assembly.STEP.zip)
