### ISSUE TITLE
Missing pads on Teensy++ 2.0 footprint.

### ISSUE THREAD

**Issue by josuegaleas** [XenGi/teensy.pretty#2]
After using the symbol found [here](https://github.com/XenGi/teensy_library) and generating/reading the net list, I got the folllowing errors:

<img width="364" alt="screen shot 2017-08-10 at 2 10 33 pm" src="https://user-images.githubusercontent.com/13757382/29192340-f6c2a3de-7dd5-11e7-815f-195776e67b79.png">

The pads 13, 53, and 54 are missing from the footprint. I noticed that where 13 should be, it says 19. In other words, there are two pad 19's. Pads 53 and 54 seem to correspond to the E4 and E5 pads shown below:

<img width="414" alt="screen shot 2017-08-10 at 2 16 56 pm" src="https://user-images.githubusercontent.com/13757382/29192691-2fd0608e-7dd7-11e7-9c07-818ce48cb412.png">

**Comment by TroyFletcher** [comment]
I have the same issue. Would a pull request to get the 13 updated be easier?

**Comment by XenGi** [comment]
Fixed it in the latest commit. Pin 13 is now in place.
I removed pins 53 and 54 because they are inaccessible from a pcb anyway. So it's pretty much useless to put them on the footprint.
