### ISSUE TITLE
Schema for Teensy LC 

### ISSUE THREAD

**Issue by jnehring** [XenGi/teensy.pretty#9]
I am a total newby in KiCad. But the part for Teensy LC seems to be broken. I can see proper parts for all Teensy models, but for Teensy LC it is empty. 
Is it my mistake or is the library damaged?

Thank you and all the best

**Comment by blackketter** [comment]
Teensy LC uses the same footprint as Teensy 3.0, 3.1 & 3.2.

**Comment by jnehring** [comment]
ok thank you for the info.
